// Getters
export const GETTERS_INIT_HEROES = "GETTERS_INIT_HEROES";
export const GETTERS_INIT_HERO = "GETTERS_INIT_HERO";

export const GETTERS_INIT_VILLAINS = "GETTERS_INIT_VILLAINS";
export const GETTERS_INIT_VILLAIN = "GETTERS_INIT_VILLAIN";

// Mutations
export const MUTATE_GET_HEROES = "MUTATE_GET_HEROES";
export const MUTATE_GET_HERO = "MUTATE_GET_HERO";
export const MUTATE_ADD_HERO = "MUTATE_ADD_HERO";
export const MUTATE_UPDATE_HERO = "MUTATE_UPDATE_HERO";
export const MUTATE_REMOVE_HERO = "MUTATE_REMOVE_HERO";

export const MUTATE_GET_VILLAINS = "MUTATE_GET_VILLAINS";
export const MUTATE_GET_VILLAIN = "MUTATE_GET_VILLAIN";
export const MUTATE_ADD_VILLAIN = "MUTATE_ADD_VILLAIN";
export const MUTATE_UPDATE_VILLAIN = "MUTATE_UPDATE_VILLAIN";
export const MUTATE_REMOVE_VILLAIN = "MUTATE_REMOVE_VILLAIN";

// Actions
export const ACTION_GET_HEROES = "ACTION_GET_HEROES";
export const ACTION_GET_HERO = "ACTION_GET_HERO";
export const ACTION_ADD_HERO = "ACTION_ADD_HERO";
export const ACTION_UPDATE_HERO = "ACTION_UPDATE_HERO";
export const ACTION_REMOVE_HERO = "ACTION_REMOVE_HERO";

export const ACTION_GET_VILLAINS = "ACTION_GET_VILLAINS";
export const ACTION_GET_VILLAIN = "ACTION_GET_VILLAIN";
export const ACTION_ADD_VILLAIN = "ACTION_ADD_VILLAIN";
export const ACTION_UPDATE_VILLAIN = "ACTION_UPDATE_VILLAIN";
export const ACTION_REMOVE_VILLAIN = "ACTION_REMOVE_VILLAIN";
